#User constants
USER_FIRSTNAME_MAXLENGTH = 64
USER_LASTNAME_MAXLENGTH = 64
USER_USERNAME_MAXLENGTH = 32
USER_PASSWORD_MAXLENGTH = 64
USER_BIO_MAXLENGHT = 256
USER_EMAIL_MAXLENGTH = 128
USER_AVATAR_MAXSIZE = 1024 * 1024 #1MB

USER_USERNAME_MINLENGTH = 6
USER_PASSW_MINLENGTH = 8

#Static constants
PROFILE_PICS_PATH = 'static/profile_pics/'
DEFAULT_PROFILE_PIC = 'default.jpeg'